### ISSUE TITLE
Feature request: XMS and EMS support toggles in the core options

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/dosbox-libretro#132]
As is, these can only be altered through conf loading, which is rather clumsy.

**Comment by MrBlastman** [comment]
You can turn ems and xms on and off by typing as such when at the command prompt:

"ems on"
"ems off"

etc.

**Comment by n1ghttrap** [comment]
Thanks, that's good enough for me, really.  Would still be nice but so long as it's possible.
