### ISSUE TITLE
savestates support (feature request)

### ISSUE THREAD

**Issue by eadmaster** [libretro/dosbox-libretro#34]
Add savestates support by implementing the `serialize` function.
Currently there is no DOS emulator with rewind support so this would be nice to have.

**Comment by fr500** [comment]
far from trivial.
There are a few dosbox forks with savestates and most fail in X or Y application

**Comment by meepingsnesroms** [comment]
Would require a complete rewrite.(ie. not dosbox anymore)

See [http://libretro.com/forums/showthread.php?t=7032&p=48553&viewfull=1#post48553](url)
