### ISSUE TITLE
Android build failing

### ISSUE THREAD

**Issue by fr500** [libretro/dosbox-libretro#48]
It seems this is not working:
https://github.com/libretro/dosbox-libretro/commit/a0edea5a2820a3cca4d4d4110225733108cdab56

http://hastebin.com/rokazuyiya

**Comment by meepingsnesroms** [comment]
I test compiled it before submitting and just now and it worked fine.
Using macos with ndk r13*

**Comment by fr500** [comment]
There must be something different in your environment because it used to build fine before.
The build command is:

BUILD CMD: ndk-build -j6 APP_ABI=armeabi-v7a

The environment variables that the buildbot uses:


```
ANDROID_HOME /home/buildbot/tools/android/android-sdk-linux
NDK_ROOT /home/buildbot/tools/android/android-ndk-r13b/
ANDROID_NDK /home/buildbot/tools/android/android-ndk-r13b/
PATH $PATH:/home/buildbot/tools/android/android-ndk-r13b:/home/buildbot/tools/android/android-sdk-linux/tools
PLATFORM android
platform android
MAKE make
NDK ndk-build
NDK_TOOLCHAIN_VERSION 4.9
LIBSUFFIX _android
```

**Comment by fr500** [comment]
Hmmm it works for ARM64
Not sure what's up with this

**Comment by fr500** [comment]
Without your patch it builds fine, so I think there is an issue on your end
I just reverted a0edea5a2820a3cca4d4d4110225733108cdab56 and it builds correctly for all ABIs

**Comment by fr500** [comment]
I reverted your patch for now, we should try to resolve this issue on your setup instead, I tried on both ubuntu buildbot and it works fine without it. Let me know if it causes any issues for you.

**Comment by meepingsnesroms** [comment]
Without it the intro is a garbled mess on Android.

I think your issue has to do with #include_next not being standard.

**Comment by meepingsnesroms** [comment]
My build environment is the same as yours without the -j6

**Comment by meepingsnesroms** [comment]
I may be using clang though.(whatever the current default is that's what I am using)

**Comment by fr500** [comment]
Even without j6 it didn't work on anything but ARM64
Yes r13 uses clang

**Comment by meepingsnesroms** [comment]
Try with clang,and if it works just use clang for this core.(have to switch eventually if you want ndk updates)

**Comment by fr500** [comment]
We ARE using clang, r13 uses clang as default for armv7a

**Comment by meepingsnesroms** [comment]
Not if ndk_toolchain_version == 4.9

**Comment by fr500** [comment]
Oh yeah good catch!
So I should just avoid setting that?
Problem is several cores don't build without that because the makefiles have the full path to the toolchain set and I don't feel like making a separate job just for one core...

It works though... not sure what to do now

**Comment by meepingsnesroms** [comment]
Leave it but set it to clang for this core.

Can you put the fix back now?

**Comment by fr500** [comment]
We don't have a way to do it per-core without doing a separate job for that core..

**Comment by meepingsnesroms** [comment]
What about putting if(core == dosbox)ndk_toolchain_version = clang; in the master makefile?(it would check every core to see what tool chain to use)

**Comment by fr500** [comment]
It's already fixed in the core
