### ISSUE TITLE
RetroPad core options not working at all

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/dosbox-libretro#54]
This core has a bunch of control options listed in the normal options menu: RetroPad X, RetroPad Y, RetroPad Start, etc.

These can be remapped to keyboard keys (ex. Left Shift, F1, etc).

This does not seem to be working. Setting any of the buttons to press a key results in nothing happening when the button is pressed.

The mouse emulation works though!

**Comment by fr500** [comment]
you need to change input device to keymapper

**Comment by hooby3dfx** [comment]
thanks, that was it!
