### ISSUE TITLE
Feature Request: Having an option to map more than one gamepad with keyboard keys

### ISSUE THREAD

**Issue by Gagert** [libretro/dosbox-libretro#57]
I've recently migrated from a custom build of DosBox to the core included in RetroArch.

It took some time setting it up to my preferences, but now one of the final things remaining from my part is mapping keyboard keys to my Xbox One controllers. I've just mapped the various Ctrl/Alt/Arrow Keys and so on from the keyboard to my Xbox One gamepad via the Options menu in the DosBox core (RetroPad Y, RetroPad X and so on).

This seems like a genius feature in this DosBox core, because then the game itself does not detect any gamepads directly while you can fully utilize a game controller anyway by emulating the keyboard (to my understanding).

How about extending that feature to include more than one gamepad/RetroPad in the Options menu of this DosBox core? There are games like Micro Machines 2 that supports 4 players at once if I'm not mistaken, but the particular game I'm thinking mostly about is the game Tyrian2k.

The problem I have with Tyrian2k in both the official and custom DosBox builds is that if you play the game in 2 player mode, and both the players want to use gamepads, there's not enough mappable gamepad buttons because of DosBox (and the restriction of MS-DOS itself) only having 2axis if two gamepads are connected, while having 4axis if you only are going to use one gamepad. That's 2 action-buttons for each player in 2 player mode and 4 action-buttons available in 1 player mode, but as I recall it Tyrian2k uses 3 action-buttons for each player.

If this DosBox core had the ability to map keyboard keys to more controllers via the options menu, then playing both Micro Machines 2 and Tyrian2k in multiplayer could be a possibility, even if the games itself have all the button mapped to the keyboard keys.

**Comment by sergiou87** [comment]
@Gagert a bit late but this should cover your request! https://github.com/libretro/dosbox-libretro/pull/85
