### ISSUE TITLE
Flashback CD-version; can't get the main menu music working (works in vanilla dosbox)

### ISSUE THREAD

**Issue by Gagert** [libretro/dosbox-libretro#62]
This is only a minor issue, but it's an issue non the less. In both the official dosbox 0.74 build and the ykwong Daum enhanced dosbox build, I'm able to hear the main menu music in the CD-version of Flashback. There are 3 different options when it comes to available music-cards in the games setup file (install.exe), and all of those works as intended in both those builds.

In the dosbox libretro core however, I can't get the main menu music working in this game with either of the 3 available music-cards. The sound-card works as intended (sound in the install.exe config), and the only disadvantage the non-working music-card gives this game is a silent main menu, as far as I know.

I have the same exact values when it comes to sound card in my dosbox-libretro.conf as the dosbox.conf file in the official dosbox 0.74 build, so this kind of puzzles me.

sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=44100

**Comment by hooby3dfx** [comment]
Does the game use redbook audio from the CD? If so is the cd image mounted as bin/cue?

**Comment by Gagert** [comment]
I just tested the floppy disc version of Flashback, and the situation is just the same there as the CD version while running the game in the dosbox libretro-core.

Main menu music works as it should in vanilla dosbox, but not via the dosbox libretro core.

**Comment by Gagert** [comment]
This seems to be fixed with the DosBox SVN build now, both on the floppy- and CD version of this game
